"use client";
import Link from "next/link";
import { useMemo, useState } from "react";

type Status="Publicado"|"Borrador"|"Agotado";
type Trip={id:string;title:string;location:string;image:string;status:Status;departure:string;capacity:number;sold:number;price:string;currency:string;duration:string;blog:boolean;itinerary:string[]};

const seed:Trip[]=[
{id:"ushuaia",title:"Ushuaia",location:"Tierra del Fuego",image:"/destinations/ushuaia.jpg",status:"Publicado",departure:"22–26 octubre",capacity:20,sold:18,price:"3.690.000",currency:"ARS",duration:"5 días / 4 noches",blog:true,itinerary:["Llegada y encuentro","Parque Nacional","Canal Beagle","Montaña y experiencia local","Regreso"]},
{id:"trevelin",title:"Trevelin · Tulipanes",location:"Chubut",image:"/destinations/trevelin.jpg",status:"Publicado",departure:"05–09 noviembre",capacity:18,sold:14,price:"3.390.000",currency:"ARS",duration:"5 días / 4 noches",blog:true,itinerary:["Llegada al glamping","Campo de tulipanes","Cultura galesa","Los Alerces","Despedida"]},
{id:"el-calafate-el-chalten",title:"El Calafate & El Chaltén",location:"Santa Cruz",image:"/packages/el-calafate.jpg",status:"Publicado",departure:"Próxima fecha",capacity:20,sold:13,price:"3.190.000",currency:"ARS",duration:"5 días / 4 noches",blog:false,itinerary:["Llegada","Perito Moreno","Navegación","El Chaltén","Regreso"]},
{id:"san-martin-de-los-andes",title:"San Martín de los Andes",location:"Neuquén",image:"/destinations/san-martin.jpg",status:"Publicado",departure:"Próxima fecha",capacity:18,sold:11,price:"2.490.000",currency:"ARS",duration:"5 días / 4 noches",blog:false,itinerary:["Llegada","Siete Lagos","Bosque","Lago Lácar","Regreso"]},
{id:"norte-argentino",title:"Norte Argentino",location:"Salta & Jujuy",image:"/packages/norte.jpg",status:"Publicado",departure:"04–10 noviembre",capacity:22,sold:16,price:"2.960.000",currency:"ARS",duration:"7 días / 6 noches",blog:false,itinerary:["Salta","Quebrada","Purmamarca","Humahuaca","Cafayate","Experiencia local","Regreso"]},
{id:"catamarca",title:"Catamarca",location:"Catamarca",image:"/destinations/catamarca.jpg",status:"Publicado",departure:"04–10 noviembre",capacity:18,sold:10,price:"3.840.000",currency:"ARS",duration:"7 días / 6 noches",blog:true,itinerary:["Llegada","Valles","Puna","Salares","Antofagasta","Montaña","Regreso"]},
{id:"new-york",title:"New York",location:"Estados Unidos",image:"/packages/new-york.jpeg",status:"Borrador",departure:"11–20 mayo",capacity:20,sold:7,price:"4.950",currency:"USD",duration:"9 días / 8 noches",blog:false,itinerary:["Llegada","Manhattan","Brooklyn","Museos","Barrios","Tiempo libre","Experiencia grupal","Último día","Regreso"]},
{id:"puerto-rico",title:"Puerto Rico",location:"Caribe",image:"/destinations/puerto-rico.jpg",status:"Publicado",departure:"Próxima salida",capacity:24,sold:21,price:"Consultar",currency:"USD",duration:"8 días / 7 noches",blog:true,itinerary:["San Juan","Viejo San Juan","Naturaleza tropical","Playa","Experiencia local","Día libre","Cierre","Regreso"]}
];

export default function CatalogoPage(){
 const [trips,setTrips]=useState(seed); const [selected,setSelected]=useState("ushuaia"); const [query,setQuery]=useState(""); const [tab,setTab]=useState<"contenido"|"operacion"|"editorial">("contenido");
 const current=trips.find(t=>t.id===selected)!; const visible=useMemo(()=>trips.filter(t=>t.title.toLowerCase().includes(query.toLowerCase())),[trips,query]); const update=(patch:Partial<Trip>)=>setTrips(v=>v.map(t=>t.id===selected?{...t,...patch}:t)); const occupancy=Math.round(current.sold/current.capacity*100);
 return <main className="cmsPage">
  <header className="cmsTopbar"><Link href="/" className="cmsBrand">Locas por la aventura</Link><nav><Link href="/">Sitio</Link><Link href="/viajes">Viajes</Link><Link href="/control">Control</Link><Link href="/catalogo" className="isActive">Catálogo</Link></nav><div className="cmsUser"><span>GG</span><div><b>Administración</b><small>Modo demo</small></div></div></header>
  <div className="cmsShell">
   <aside className="cmsSidebar"><div className="cmsSideTitle"><span>GESTIÓN</span><h1>Catálogo</h1></div><button className="cmsNew">＋ Nuevo viaje</button><label className="cmsSearch">⌕<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar viaje"/></label><div className="cmsTripList">{visible.map(t=><button key={t.id} onClick={()=>setSelected(t.id)} className={selected===t.id?"isSelected":""}><img src={t.image} alt=""/><div><b>{t.title}</b><small>{t.departure}</small></div><i className={`status ${t.status.toLowerCase()}`}/></button>)}</div></aside>
   <section className="cmsMain">
    <div className="cmsHeaderRow"><div><span>CATÁLOGO / {current.status.toUpperCase()}</span><h2>{current.title}</h2><p>{current.location} · {current.duration}</p></div><div className="cmsHeaderActions"><Link href={`/viajes/${current.id}`} target="_blank">Vista previa ↗</Link><button onClick={()=>update({status:current.status==="Publicado"?"Borrador":"Publicado"})}>{current.status==="Publicado"?"Despublicar":"Publicar"}</button></div></div>
    <div className="cmsStats"><article><span>Próxima salida</span><strong>{current.departure}</strong></article><article><span>Ocupación</span><strong>{current.sold}/{current.capacity}</strong><em>{occupancy}%</em></article><article><span>Disponibles</span><strong>{current.capacity-current.sold}</strong></article><article><span>Precio</span><strong>{current.price==="Consultar"?"Consultar":`${current.currency} ${current.price}`}</strong></article></div>
    <div className="cmsTabs"><button onClick={()=>setTab("contenido")} className={tab==="contenido"?"active":""}>Contenido</button><button onClick={()=>setTab("operacion")} className={tab==="operacion"?"active":""}>Salidas y cupos</button><button onClick={()=>setTab("editorial")} className={tab==="editorial"?"active":""}>Blog & prueba social</button></div>
    {tab==="contenido"&&<div className="cmsTwoCols">
      <section className="cmsCard"><div className="cmsCardHead"><h3>Información principal</h3><span>WEB PÚBLICA</span></div><label>Título<input value={current.title} onChange={e=>update({title:e.target.value})}/></label><div className="cmsFieldGrid"><label>Destino<input value={current.location} onChange={e=>update({location:e.target.value})}/></label><label>Duración<input value={current.duration} onChange={e=>update({duration:e.target.value})}/></label></div><label>Portada<div className="cmsImageField"><img src={current.image} alt=""/><span>{current.image}</span><button>Cambiar</button></div></label></section>
      <section className="cmsCard"><div className="cmsCardHead"><h3>Itinerario</h3><button>＋ Agregar día</button></div><div className="cmsDays">{current.itinerary.map((d,i)=><div key={i}><span>{String(i+1).padStart(2,"0")}</span><input value={d} onChange={e=>{const n=[...current.itinerary];n[i]=e.target.value;update({itinerary:n})}}/><button>⋮</button></div>)}</div></section>
      <section className="cmsCard"><div className="cmsCardHead"><h3>Incluye / No incluye</h3><button>Editar</button></div><ul className="cmsChecklist"><li>✓ Alojamiento seleccionado</li><li>✓ Traslados previstos</li><li>✓ Coordinación permanente</li><li>○ Gastos personales</li></ul></section>
      <section className="cmsCard"><div className="cmsCardHead"><h3>Documentación</h3><button>＋ Agregar</button></div><ul className="cmsChecklist"><li>▣ Documento vigente</li><li>▣ Contacto de emergencia</li><li>▣ Seguro de viaje cuando corresponda</li></ul></section>
    </div>}
    {tab==="operacion"&&<div className="cmsTwoCols">
      <section className="cmsCard"><div className="cmsCardHead"><h3>Salida activa</h3><span>OPERACIÓN</span></div><label>Fecha / salida<input value={current.departure} onChange={e=>update({departure:e.target.value})}/></label><div className="cmsFieldGrid"><label>Cupo total<input type="number" value={current.capacity} onChange={e=>update({capacity:+e.target.value})}/></label><label>Vendidos<input type="number" value={current.sold} onChange={e=>update({sold:+e.target.value})}/></label></div><div className="cmsCapacity"><div><span style={{width:`${Math.min(occupancy,100)}%`}}/></div><p>{occupancy}% ocupado · {Math.max(current.capacity-current.sold,0)} lugares disponibles</p></div></section>
      <section className="cmsCard"><div className="cmsCardHead"><h3>Precio y estado</h3><span>VENTA</span></div><div className="cmsFieldGrid"><label>Moneda<select value={current.currency} onChange={e=>update({currency:e.target.value})}><option>ARS</option><option>USD</option><option>EUR</option></select></label><label>Precio<input value={current.price} onChange={e=>update({price:e.target.value})}/></label></div><label>Estado<select value={current.status} onChange={e=>update({status:e.target.value as Status})}><option>Publicado</option><option>Borrador</option><option>Agotado</option></select></label></section>
      <section className="cmsCard cmsAutomation"><div className="cmsCardHead"><h3>Automatizaciones ligadas</h3><span>ACTIVAS</span></div><div><b>Últimos cupos</b><p>Al llegar a 3 lugares disponibles activa avisos para leads interesados.</p></div><div><b>Lista de espera</b><p>Al completar cupo cambia el CTA y captura lista de espera.</p></div><div><b>Nueva salida</b><p>Una fecha nueva puede avisar a favoritas e interesadas.</p></div></section>
    </div>}
    {tab==="editorial"&&<div className="cmsTwoCols">
      <section className="cmsCard cmsEditorial"><div className="cmsCardHead"><h3>Artículo del destino</h3><span>{current.blog?"PUBLICADO":"PENDIENTE"}</span></div><div className="cmsArticlePreview"><img src={current.image} alt=""/><div><small>REVISTA LOCAS</small><h4>Qué nos enamora de {current.title}</h4><p>Historia, clima, qué hacer, experiencias y contenido editorial asociado al viaje.</p><Link href={`/blog/${current.id}`} target="_blank">Abrir artículo ↗</Link></div></div></section>
      <section className="cmsCard"><div className="cmsCardHead"><h3>Testimonios</h3><button>＋ Agregar</button></div><div className="cmsBigNumber">12</div><p className="cmsMuted">historias asociadas a este destino</p><div className="cmsReview"><b>★★★★★</b><p>“El grupo fue una parte enorme del viaje. Volví con amigas y con ganas de elegir el próximo destino juntas.”</p><small>Pasajera · viaje anterior</small></div></section>
      <section className="cmsCard"><div className="cmsCardHead"><h3>Estado de contenido</h3><span>7/8 LISTO</span></div><div className="cmsContentState"><p>✓ Portada</p><p>✓ Itinerario</p><p>✓ Incluye</p><p>✓ Documentación</p><p>✓ Fotos</p><p>✓ SEO</p><p>✓ Testimonios</p><p className={!current.blog?"pending":""}>{current.blog?"✓":"○"} Blog</p></div></section>
    </div>}
   </section>
  </div>
 </main>
}
