"use client";

import { useMemo, useState } from "react";
import Link from "next/link";
import { CalendarDays, CheckCircle2, CircleDollarSign, Edit3, Plus, Search, UsersRound, X } from "lucide-react";
import { createSupabaseClient } from "@/lib/supabase/client";

type Row={id:string;contact_id:string;departure_id:string|null;status:string;travelers:number;room_type:string|null;total_amount:number|null;paid_amount:number|null;currency:string|null;reserved_at:string;contact_name:string;email:string;phone:string;trip_name:string;starts_on:string|null;owner_name:string};
type Contact={id:string;name:string;email:string;phone:string;owner_name:string};
type Departure={id:string;trip_name:string;starts_on:string|null;currency:string|null;price:number|null;capacity:number;sold:number};

const statuses=["pending","reserved","confirmed","cancelled"];
const statusLabel:Record<string,string>={pending:"Pendiente",reserved:"Reservada",confirmed:"Confirmada",cancelled:"Cancelada"};

export default function ReservationsClient({initial,contacts,departures}:{initial:Row[];contacts:Contact[];departures:Departure[]}){
 const [rows,setRows]=useState(initial); const [query,setQuery]=useState(""); const [filter,setFilter]=useState("all"); const [open,setOpen]=useState(false); const [editing,setEditing]=useState<Row|null>(null); const [saving,setSaving]=useState(false);
 const [contactId,setContactId]=useState(contacts[0]?.id||""); const [departureId,setDepartureId]=useState(departures[0]?.id||""); const [status,setStatus]=useState("pending"); const [travelers,setTravelers]=useState(1); const [roomType,setRoomType]=useState("Doble"); const [total,setTotal]=useState(0); const [paid,setPaid]=useState(0); const [currency,setCurrency]=useState("ARS");
 const supabase=createSupabaseClient();
 const visible=useMemo(()=>rows.filter(r=>{const q=query.toLowerCase();return (!q||`${r.contact_name} ${r.trip_name} ${r.email}`.toLowerCase().includes(q))&&(filter==="all"||r.status===filter)}),[rows,query,filter]);
 const pendingBalance=rows.reduce((s,r)=>s+Math.max(Number(r.total_amount||0)-Number(r.paid_amount||0),0),0); const confirmed=rows.filter(r=>r.status==="confirmed").length; const travelersTotal=rows.filter(r=>r.status!=="cancelled").reduce((s,r)=>s+Number(r.travelers||0),0);
 const fmt=(n:number,c="ARS")=>`${c} ${Number(n||0).toLocaleString("es-AR")}`;
 const startCreate=()=>{setEditing(null);setContactId(contacts[0]?.id||"");setDepartureId(departures[0]?.id||"");setStatus("pending");setTravelers(1);setRoomType("Doble");const d=departures[0];setTotal(Number(d?.price||0));setPaid(0);setCurrency(d?.currency||"ARS");setOpen(true)};
 const startEdit=(r:Row)=>{setEditing(r);setContactId(r.contact_id);setDepartureId(r.departure_id||"");setStatus(r.status);setTravelers(r.travelers||1);setRoomType(r.room_type||"Doble");setTotal(Number(r.total_amount||0));setPaid(Number(r.paid_amount||0));setCurrency(r.currency||"ARS");setOpen(true)};
 const changeDeparture=(id:string)=>{setDepartureId(id);const d=departures.find(x=>x.id===id);if(d){setTotal(Number(d.price||0));setCurrency(d.currency||"ARS")}};
 const save=async()=>{if(!contactId)return;setSaving(true);const payload={contact_id:contactId,departure_id:departureId||null,status,travelers,room_type:roomType,total_amount:total,paid_amount:paid,currency,reserved_at:editing?.reserved_at||new Date().toISOString()};let result:any;if(editing) result=await supabase.from("reservations").update(payload).eq("id",editing.id).select("id").single(); else result=await supabase.from("reservations").insert(payload).select("id").single();if(!result.error){const c=contacts.find(x=>x.id===contactId);const d=departures.find(x=>x.id===departureId);const next:Row={id:editing?.id||result.data.id,...payload,contact_name:c?.name||"Sin pasajera",email:c?.email||"",phone:c?.phone||"",trip_name:d?.trip_name||"—",starts_on:d?.starts_on||null,owner_name:c?.owner_name||"Sin asignar"};setRows(prev=>editing?prev.map(x=>x.id===editing.id?next:x):[next,...prev]);setOpen(false)}setSaving(false)};
 return <>
  <section className="reservationMetrics">
   <article><span>Reservas</span><strong>{rows.length}</strong><small>Total registradas</small></article>
   <article><span>Confirmadas</span><strong>{confirmed}</strong><small>{rows.length?Math.round(confirmed*100/rows.length):0}% del total</small></article>
   <article><span>Pasajeras</span><strong>{travelersTotal}</strong><small>Sin canceladas</small></article>
   <article><span>Saldo pendiente</span><strong>{fmt(pendingBalance,rows.find(r=>r.currency)?.currency||"ARS")}</strong><small>Por cobrar</small></article>
  </section>
  <section className="opsCard reservationWorkspace">
   <div className="reservationToolbar"><label><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar pasajera, viaje o email"/></label><div className="reservationFilters"><button className={filter==="all"?"active":""} onClick={()=>setFilter("all")}>Todas</button>{statuses.map(s=><button key={s} className={filter===s?"active":""} onClick={()=>setFilter(s)}>{statusLabel[s]}</button>)}</div><button className="opsPrimaryBtn" onClick={startCreate}><Plus size={16}/> Nueva reserva</button></div>
   <div className="reservationTable"><div className="head"><span>Pasajera</span><span>Viaje / salida</span><span>Responsable</span><span>Importe</span><span>Saldo</span><span>Estado</span><span/></div>{visible.map(r=>{const balance=Math.max(Number(r.total_amount||0)-Number(r.paid_amount||0),0);return <div key={r.id}><span><b>{r.contact_name}</b><small>{r.email||r.phone||"Sin contacto"}</small></span><span><b>{r.trip_name}</b><small>{r.starts_on?new Date(`${r.starts_on}T12:00:00`).toLocaleDateString("es-AR"):"Sin fecha"} · {r.travelers} pasajera(s)</small></span><span><b>{r.owner_name}</b><small>{r.room_type||"Sin habitación"}</small></span><span><b>{fmt(Number(r.total_amount||0),r.currency||"ARS")}</b><small>Pagado {fmt(Number(r.paid_amount||0),r.currency||"ARS")}</small></span><span className={balance>0?"balance due":"balance paid"}><b>{fmt(balance,r.currency||"ARS")}</b><small>{balance>0?"Pendiente":"Saldado"}</small></span><span><em className={`reservationStatus ${r.status}`}>{statusLabel[r.status]||r.status}</em></span><span className="reservationActions"><Link href={`/crm/contacto/${r.contact_id}`} title="Ficha CRM"><UsersRound size={16}/></Link><button onClick={()=>startEdit(r)} title="Editar"><Edit3 size={16}/></button></span></div>})}{!visible.length&&<p className="opsEmptyRow">No hay reservas con este filtro.</p>}</div>
  </section>
  {open&&<div className="reservationBackdrop" onClick={()=>setOpen(false)}><aside className="reservationDrawer" onClick={e=>e.stopPropagation()}><header><div><small>RESERVAS</small><h2>{editing?"Editar reserva":"Nueva reserva"}</h2></div><button className="opsIconBtn" onClick={()=>setOpen(false)}><X size={17}/></button></header><div className="reservationForm"><label>Pasajera<select value={contactId} onChange={e=>setContactId(e.target.value)}>{contacts.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Salida<select value={departureId} onChange={e=>changeDeparture(e.target.value)}>{departures.map(d=><option key={d.id} value={d.id}>{d.trip_name} · {d.starts_on||"sin fecha"}</option>)}</select></label><div className="reservationFormGrid"><label>Estado<select value={status} onChange={e=>setStatus(e.target.value)}>{statuses.map(s=><option key={s} value={s}>{statusLabel[s]}</option>)}</select></label><label>Pasajeras<input type="number" min="1" value={travelers} onChange={e=>setTravelers(Number(e.target.value))}/></label></div><label>Habitación<input value={roomType} onChange={e=>setRoomType(e.target.value)} placeholder="Doble, single..."/></label><div className="reservationFormGrid"><label>Moneda<select value={currency} onChange={e=>setCurrency(e.target.value)}><option>ARS</option><option>USD</option><option>EUR</option></select></label><label>Total<input type="number" value={total} onChange={e=>setTotal(Number(e.target.value))}/></label></div><label>Pagado<input type="number" value={paid} onChange={e=>setPaid(Number(e.target.value))}/></label><div className="reservationBalance"><CircleDollarSign size={18}/><div><span>Saldo</span><b>{fmt(Math.max(total-paid,0),currency)}</b></div></div><button className="opsPrimaryBtn save" disabled={saving} onClick={save}>{saving?"Guardando...":editing?"Guardar cambios":"Crear reserva"}</button></div></aside></div>}
 </>;
}
