"use client";
import Link from "next/link";
import { useMemo,useState } from "react";

type Thread={id:string;contact_id:string|null;channel:string;subject:string|null;status:string;unread_count:number;last_message_at:string;contact_name:string|null;email:string|null;phone:string|null;last_message:string|null;intent:string|null;sentiment:string|null};
type Message={id:string;conversation_id:string;channel:string;direction:string;sender_name:string|null;body:string|null;subject:string|null;status:string|null;sent_at:string;message_type:string};
const channelLabel:Record<string,string>={whatsapp:"WhatsApp",instagram:"Instagram",messenger:"Messenger",email:"Email"};
export default function InboxClient({threads,messages}:{threads:Thread[];messages:Message[]}){
 const [channel,setChannel]=useState("Todos"),[query,setQuery]=useState(""),[selected,setSelected]=useState(threads[0]?.id||"");
 const list=useMemo(()=>threads.filter(t=>(channel==="Todos"||t.channel===channel)&&(`${t.contact_name||""} ${t.last_message||""} ${t.subject||""}`.toLowerCase().includes(query.toLowerCase()))),[threads,channel,query]);
 const current=threads.find(t=>t.id===selected)||list[0]; const conversation=current?messages.filter(m=>m.conversation_id===current.id):[];
 const counts=threads.reduce((a,t)=>{a[t.channel]=(a[t.channel]||0)+1;return a},{} as Record<string,number>);
 return <main className="inboxPage">
  <header className="crmTopbar"><Link href="/" className="crmBrand">Locas por la aventura</Link><nav><Link href="/catalogo">Catálogo</Link><Link href="/crm">CRM</Link><Link href="/crm/mensajes" className="isActive">Mensajes</Link><Link href="/control">Control</Link></nav><div className="crmUser"><span>GG</span><div><b>Administración</b><small>Bandeja unificada</small></div></div></header>
  <section className="inboxShell"><div className="inboxHead"><div><span>CRM / COMUNICACIONES</span><h1>Todos los mensajes, una sola persona.</h1><p>WhatsApp, Instagram, Messenger y email unidos al historial comercial del contacto.</p></div><div className="inboxKpis"><b>{threads.length}<small> conversaciones</small></b><b>{threads.reduce((a,t)=>a+Number(t.unread_count||0),0)}<small> sin leer</small></b></div></div>
  <div className="inboxFilters"><label>⌕ <input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar persona o mensaje"/></label><div>{["Todos","whatsapp","instagram","messenger","email"].map(c=><button key={c} onClick={()=>setChannel(c)} className={channel===c?"active":""}>{c==="Todos"?"Todos":channelLabel[c]} {c!=="Todos"&&<small>{counts[c]||0}</small>}</button>)}</div></div>
  <div className="inboxWorkspace"><aside className="inboxThreads">{list.map(t=><button key={t.id} className={selected===t.id?"selected":""} onClick={()=>setSelected(t.id)}><span className={`inboxChannel ${t.channel}`}>{channelLabel[t.channel]||t.channel}</span><div><b>{t.contact_name||"Contacto sin identificar"}</b><p>{t.last_message||t.subject||"Sin mensaje"}</p><small>{new Date(t.last_message_at).toLocaleString("es-AR")}</small></div>{t.unread_count>0&&<i>{t.unread_count}</i>}</button>)}</aside>
  <section className="inboxConversation">{current?<><header><div><span className={`inboxChannel ${current.channel}`}>{channelLabel[current.channel]||current.channel}</span><h2>{current.contact_name||"Contacto"}</h2><p>{current.email||current.phone||""}</p></div><Link href={`/crm?contact=${current.contact_id||""}`}>Ver ficha CRM ↗</Link></header><div className="inboxMessages">{conversation.map(m=><article key={m.id} className={m.direction==="outbound"?"outbound":"inbound"}><span>{m.sender_name||channelLabel[m.channel]||m.channel}</span>{m.subject&&<b>{m.subject}</b>}<p>{m.body}</p><small>{new Date(m.sent_at).toLocaleString("es-AR")}</small></article>)}</div><footer><textarea placeholder="Responder desde el CRM (demo)"/><button>Enviar</button></footer></>:<div className="inboxEmpty">No hay conversaciones.</div>}</section>
  <aside className="inboxContext">{current&&<><span>CONTEXTO</span><h3>{current.contact_name}</h3><div><small>Canal</small><b>{channelLabel[current.channel]||current.channel}</b></div><div><small>Estado</small><b>{current.status}</b></div><div><small>Intención</small><b>{current.intent||"Pendiente de clasificar"}</b></div><div><small>Sentimiento</small><b>{current.sentiment||"Sin clasificar"}</b></div><div><small>Último mensaje</small><p>{current.last_message}</p></div><button>Crear tarea de seguimiento</button></>}</aside></div></section>
 </main>
}
