"use client";

import { useMemo, useState } from "react";
import { CheckCircle2, CircleDollarSign, Edit3, Plus, Search, X } from "lucide-react";
import { createSupabaseClient } from "@/lib/supabase/client";

type Row={id:string;reservation_id:string;status:string;amount:number;currency:string;due_at:string|null;paid_at:string|null;payment_type:string|null;provider:string|null;contact_name:string;trip_name:string};
type Reservation={id:string;label:string;currency:string;balance:number};
const labels:Record<string,string>={pending:"Pendiente",paid:"Pagado",overdue:"Vencido",cancelled:"Cancelado"};
export default function PaymentsClient({initial,reservations}:{initial:Row[];reservations:Reservation[]}){
 const [rows,setRows]=useState(initial); const [query,setQuery]=useState(""); const [filter,setFilter]=useState("all"); const [open,setOpen]=useState(false); const [editing,setEditing]=useState<Row|null>(null); const [saving,setSaving]=useState(false); const s=createSupabaseClient();
 const [reservationId,setReservationId]=useState(reservations[0]?.id||""); const [amount,setAmount]=useState(reservations[0]?.balance||0); const [currency,setCurrency]=useState(reservations[0]?.currency||"ARS"); const [status,setStatus]=useState("pending"); const [provider,setProvider]=useState("Mercado Pago"); const [paymentType,setPaymentType]=useState("Seña"); const [dueAt,setDueAt]=useState("");
 const fmt=(n:number,c="ARS")=>`${c} ${Number(n||0).toLocaleString("es-AR")}`; const today=new Date();
 const normalized=rows.map(r=>({...r,displayStatus:r.status==="pending"&&r.due_at&&new Date(r.due_at)<today?"overdue":r.status}));
 const visible=useMemo(()=>normalized.filter(r=>{const q=query.toLowerCase();return (!q||`${r.contact_name} ${r.trip_name} ${r.provider} ${r.payment_type}`.toLowerCase().includes(q))&&(filter==="all"||r.displayStatus===filter)}),[rows,query,filter]);
 const total=rows.reduce((a,r)=>a+Number(r.amount||0),0); const paid=rows.filter(r=>r.status==="paid").reduce((a,r)=>a+Number(r.amount||0),0); const overdue=normalized.filter(r=>r.displayStatus==="overdue").reduce((a,r)=>a+Number(r.amount||0),0);
 const startCreate=()=>{setEditing(null);const r=reservations[0];setReservationId(r?.id||"");setAmount(r?.balance||0);setCurrency(r?.currency||"ARS");setStatus("pending");setProvider("Mercado Pago");setPaymentType("Seña");setDueAt("");setOpen(true)};
 const startEdit=(r:Row)=>{setEditing(r);setReservationId(r.reservation_id);setAmount(r.amount);setCurrency(r.currency);setStatus(r.status);setProvider(r.provider||"");setPaymentType(r.payment_type||"");setDueAt(r.due_at?r.due_at.slice(0,16):"");setOpen(true)};
 const selectReservation=(id:string)=>{setReservationId(id);const r=reservations.find(x=>x.id===id);if(r){setAmount(r.balance);setCurrency(r.currency)}};
 const save=async()=>{if(!reservationId)return;setSaving(true);const payload={reservation_id:reservationId,amount,currency,status,provider:provider||null,payment_type:paymentType||null,due_at:dueAt?new Date(dueAt).toISOString():null,paid_at:status==="paid"?(editing?.paid_at||new Date().toISOString()):null};let res:any;if(editing)res=await s.from("payments").update(payload).eq("id",editing.id).select("id").single();else res=await s.from("payments").insert(payload).select("id").single();if(!res.error){const rr=reservations.find(x=>x.id===reservationId);const parts=(rr?.label||"— · —").split(" · ");const next:Row={id:editing?.id||res.data.id,...payload,contact_name:parts[0]||"—",trip_name:parts.slice(1).join(" · ")||"—"};setRows(prev=>editing?prev.map(x=>x.id===editing.id?next:x):[next,...prev]);setOpen(false)}setSaving(false)};
 return <>
  <section className="paymentMetrics"><article><span>Programado</span><strong>{fmt(total,rows[0]?.currency||"ARS")}</strong><small>{rows.length} movimientos</small></article><article><span>Cobrado</span><strong>{fmt(paid,rows[0]?.currency||"ARS")}</strong><small>{rows.filter(r=>r.status==="paid").length} acreditados</small></article><article><span>Vencido</span><strong>{fmt(overdue,rows[0]?.currency||"ARS")}</strong><small>Requiere seguimiento</small></article><article><span>Conversión</span><strong>{total?Math.round(paid*100/total):0}%</strong><small>Cobrado / programado</small></article></section>
  <section className="opsCard paymentWorkspace"><div className="paymentToolbar"><label><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar pasajera, viaje o proveedor"/></label><div>{["all","pending","paid","overdue","cancelled"].map(x=><button key={x} className={filter===x?"active":""} onClick={()=>setFilter(x)}>{x==="all"?"Todos":labels[x]}</button>)}</div><button className="opsPrimaryBtn" onClick={startCreate}><Plus size={16}/> Registrar pago</button></div><div className="paymentTable"><div className="head"><span>Pasajera</span><span>Viaje</span><span>Concepto</span><span>Monto</span><span>Vencimiento</span><span>Estado</span><span/></div>{visible.map(r=><div key={r.id}><span><b>{r.contact_name}</b><small>{r.provider||"Sin proveedor"}</small></span><span><b>{r.trip_name}</b><small>{r.currency}</small></span><span><b>{r.payment_type||"Pago"}</b><small>{r.provider||"—"}</small></span><span><b>{fmt(r.amount,r.currency)}</b><small>{r.paid_at?`Pagado ${new Date(r.paid_at).toLocaleDateString("es-AR")}`:"Sin acreditar"}</small></span><span><b>{r.due_at?new Date(r.due_at).toLocaleDateString("es-AR"):"Sin fecha"}</b></span><span><em className={`paymentStatus ${r.displayStatus}`}>{labels[r.displayStatus]||r.displayStatus}</em></span><span className="paymentActions"><button onClick={()=>startEdit(r)}><Edit3 size={16}/></button></span></div>)}</div></section>
  {open&&<div className="paymentBackdrop" onClick={()=>setOpen(false)}><aside className="paymentDrawer" onClick={e=>e.stopPropagation()}><header><div><small>PAGOS</small><h2>{editing?"Editar movimiento":"Registrar pago"}</h2></div><button className="opsIconBtn" onClick={()=>setOpen(false)}><X size={17}/></button></header><div className="paymentForm"><label>Reserva<select value={reservationId} onChange={e=>selectReservation(e.target.value)}>{reservations.map(r=><option key={r.id} value={r.id}>{r.label}</option>)}</select></label><div className="paymentFormGrid"><label>Concepto<input value={paymentType} onChange={e=>setPaymentType(e.target.value)}/></label><label>Proveedor<select value={provider} onChange={e=>setProvider(e.target.value)}><option>Mercado Pago</option><option>Stripe</option><option>PayPal</option><option>Transferencia</option><option>Efectivo</option></select></label></div><div className="paymentFormGrid"><label>Moneda<select value={currency} onChange={e=>setCurrency(e.target.value)}><option>ARS</option><option>USD</option><option>EUR</option></select></label><label>Monto<input type="number" value={amount} onChange={e=>setAmount(Number(e.target.value))}/></label></div><div className="paymentFormGrid"><label>Estado<select value={status} onChange={e=>setStatus(e.target.value)}><option value="pending">Pendiente</option><option value="paid">Pagado</option><option value="cancelled">Cancelado</option></select></label><label>Vencimiento<input type="datetime-local" value={dueAt} onChange={e=>setDueAt(e.target.value)}/></label></div><div className="paymentSummary"><CircleDollarSign size={18}/><div><span>Movimiento</span><b>{fmt(amount,currency)}</b></div>{status==="paid"&&<CheckCircle2 size={18}/>}</div><button className="opsPrimaryBtn save" disabled={saving} onClick={save}>{saving?"Guardando...":editing?"Guardar cambios":"Registrar pago"}</button></div></aside></div>}
 </>;
}
