"use client";
import { useMemo,useState } from "react";
import { createSupabaseClient } from "@/lib/supabase/client";
import { CircleHelp, Heart, Map, MessageCircle, Plus, Search, Sparkles, UserPlus, UsersRound, X } from "lucide-react";

type Category={id:string;slug:string;name:string;description:string|null;icon:string|null};
type Member={id:string;display_name:string;city:string|null;country:string|null};
type Post={id:string;category_id:string|null;author_id:string|null;title:string;body:string;trip_slug:string|null;post_type:string;is_pinned:boolean;reply_count:number;like_count:number;created_at:string;community_categories:any;community_members:any};
const icons:any={general:UsersRound,"busco-companera":UserPlus,"proximos-viajes":Map,experiencias:Sparkles,dudas:CircleHelp};
export default function CommunityClient({initialCategories,initialPosts,members}:{initialCategories:Category[];initialPosts:Post[];members:Member[]}){
 const s=createSupabaseClient(); const [posts,setPosts]=useState(initialPosts); const [category,setCategory]=useState("all"); const [query,setQuery]=useState(""); const [showNew,setShowNew]=useState(false); const [selected,setSelected]=useState<Post|null>(null); const [comments,setComments]=useState<any[]>([]); const [reply,setReply]=useState("");
 const [title,setTitle]=useState(""); const [body,setBody]=useState(""); const [newCategory,setNewCategory]=useState(initialCategories[0]?.id||""); const [newType,setNewType]=useState("discussion"); const currentMember=members[0];
 const filtered=useMemo(()=>posts.filter(p=>(category==="all"||p.community_categories?.slug===category)&&(!query||`${p.title} ${p.body}`.toLowerCase().includes(query.toLowerCase()))),[posts,category,query]);
 async function createPost(){if(!title.trim()||!body.trim()||!currentMember)return;const {data,error}=await s.from("community_posts").insert({category_id:newCategory,author_id:currentMember.id,title:title.trim(),body:body.trim(),post_type:newType}).select("*,community_categories(id,name,slug),community_members(id,display_name,city,country)").single();if(!error&&data){setPosts([data,...posts]);setTitle("");setBody("");setShowNew(false)}}
 async function openPost(p:Post){setSelected(p);const {data}=await s.from("community_comments").select("*,community_members(display_name,city)").eq("post_id",p.id).order("created_at");setComments(data||[])}
 async function addReply(){if(!selected||!reply.trim()||!currentMember)return;const {data,error}=await s.from("community_comments").insert({post_id:selected.id,author_id:currentMember.id,body:reply.trim()}).select("*,community_members(display_name,city)").single();if(!error&&data){setComments([...comments,data]);setReply("");await s.from("community_posts").update({reply_count:(selected.reply_count||0)+1}).eq("id",selected.id);setPosts(posts.map(p=>p.id===selected.id?{...p,reply_count:(p.reply_count||0)+1}:p));setSelected({...selected,reply_count:(selected.reply_count||0)+1})}}
 return <div className="communityShell shell">
  <section className="communityHero"><div><span>COMUNIDAD LOCAS</span><h1>Conocerse también es parte del viaje.</h1><p>Un espacio para conversar, encontrar compañeras, resolver dudas y seguir compartiendo después de volver.</p></div><button onClick={()=>setShowNew(true)}><Plus size={18}/>Nueva publicación</button></section>
  <section className="communityLayout">
   <aside className="communitySidebar"><b>ESPACIOS</b><button className={category==="all"?"active":""} onClick={()=>setCategory("all")}><UsersRound size={17}/>Todo</button>{initialCategories.map(c=>{const Icon=icons[c.slug]||MessageCircle;return <button key={c.id} className={category===c.slug?"active":""} onClick={()=>setCategory(c.slug)}><Icon size={17}/><span>{c.name}<small>{c.description}</small></span></button>})}<div className="communityMemberMini"><span>{currentMember?.display_name?.split(" ").map(x=>x[0]).join("")||"L"}</span><div><b>{currentMember?.display_name||"Lucía"}</b><small>{currentMember?.city||"Argentina"}</small></div></div></aside>
   <div className="communityFeed"><label className="communitySearch"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar conversaciones..."/></label>{filtered.map(p=>{const author=p.community_members;const cat=p.community_categories;return <article key={p.id} className="communityPost" onClick={()=>openPost(p)}><div className="communityPostTop"><span className="communityAvatar">{(author?.display_name||"L").split(" ").map((x:string)=>x[0]).slice(0,2).join("")}</span><div><b>{author?.display_name||"Comunidad Locas"}</b><small>{author?.city||""} · {new Date(p.created_at).toLocaleString("es-AR",{day:"2-digit",month:"short",hour:"2-digit",minute:"2-digit"})}</small></div>{p.is_pinned&&<em>Fijado</em>}</div><span className="communityCategory">{cat?.name||"General"}</span><h2>{p.title}</h2><p>{p.body}</p><footer><span><MessageCircle size={15}/>{p.reply_count||0} respuestas</span><span><Heart size={15}/>{p.like_count||0}</span>{p.trip_slug&&<a href={`/viajes/${p.trip_slug}`} onClick={e=>e.stopPropagation()}>Ver viaje →</a>}</footer></article>})}</div>
   <aside className="communityRight"><div><span>AHORA</span><strong>{members.length}</strong><p>integrantes en esta comunidad demo</p></div><div><span>CONVERSACIONES</span><strong>{posts.length}</strong><p>temas activos</p></div><div className="communityRules"><b>Una comunidad cuidada</b><p>Respeto, información útil y conversaciones que ayuden a viajar mejor juntas.</p></div></aside>
  </section>
  {showNew&&<div className="communityModalBackdrop" onClick={()=>setShowNew(false)}><div className="communityModal" onClick={e=>e.stopPropagation()}><header><div><small>COMUNIDAD</small><h2>Nueva publicación</h2></div><button onClick={()=>setShowNew(false)}><X/></button></header><label>Espacio<select value={newCategory} onChange={e=>setNewCategory(e.target.value)}>{initialCategories.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></label><label>Tipo<select value={newType} onChange={e=>setNewType(e.target.value)}><option value="discussion">Conversación</option><option value="question">Pregunta</option><option value="companion">Busco compañera</option><option value="experience">Experiencia</option></select></label><label>Título<input value={title} onChange={e=>setTitle(e.target.value)} placeholder="¿De qué querés hablar?"/></label><label>Mensaje<textarea value={body} onChange={e=>setBody(e.target.value)} placeholder="Contale a la comunidad..."/></label><button className="communityPrimary" onClick={createPost}>Publicar</button></div></div>}
  {selected&&<div className="communityModalBackdrop" onClick={()=>setSelected(null)}><div className="communityThread" onClick={e=>e.stopPropagation()}><header><div><small>{selected.community_categories?.name||"General"}</small><h2>{selected.title}</h2></div><button onClick={()=>setSelected(null)}><X/></button></header><div className="communityThreadOriginal"><b>{selected.community_members?.display_name||"Comunidad Locas"}</b><p>{selected.body}</p></div><div className="communityComments">{comments.map(c=><div key={c.id}><span>{(c.community_members?.display_name||"L")[0]}</span><div><b>{c.community_members?.display_name||"Loca viajera"}</b><p>{c.body}</p><small>{new Date(c.created_at).toLocaleString("es-AR")}</small></div></div>)}</div><div className="communityReply"><textarea value={reply} onChange={e=>setReply(e.target.value)} placeholder="Responder a la conversación..."/><button onClick={addReply}>Responder</button></div></div></div>}
 </div>
}
