"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { createSupabaseClient } from "@/lib/supabase/client";
import { CheckCircle2, CircleAlert, Clock3, ListTodo, Plus, Search, RotateCcw, X } from "lucide-react";

type Task = { id:string; title:string; due_at:string|null; priority:string|null; status:string|null; task_type:string|null; contact_id:string|null; owner_id:string|null; opportunity_id:string|null; contact_name:string; owner_name:string; trip_name:string };
type Option = { id:string; name:string };
const fieldStyle:React.CSSProperties={height:40,border:"1px solid #dfe3e8",borderRadius:8,padding:"0 10px",background:"#fff",font:"inherit"};

export default function TasksClient({initial,contacts,owners}:{initial:Task[];contacts:Option[];owners:Option[]}){
 const [rows,setRows]=useState(initial),[filter,setFilter]=useState("open"),[query,setQuery]=useState(""),[showForm,setShowForm]=useState(false),[editing,setEditing]=useState<Task|null>(null);
 const [title,setTitle]=useState(""),[priority,setPriority]=useState("normal"),[dueAt,setDueAt]=useState(""),[contactId,setContactId]=useState(""),[ownerId,setOwnerId]=useState(""),[taskType,setTaskType]=useState("follow_up"),[saving,setSaving]=useState(false);
 const supabase=createSupabaseClient();
 const isOverdue=(t:Task)=>Boolean(t.due_at&&new Date(t.due_at).getTime()<Date.now()&&t.status!=="done");
 const isToday=(t:Task)=>{if(!t.due_at)return false;const d=new Date(t.due_at),n=new Date();return d.toDateString()===n.toDateString()};
 const stats={open:rows.filter(x=>x.status!=="done").length,today:rows.filter(isToday).length,overdue:rows.filter(isOverdue).length,done:rows.filter(x=>x.status==="done").length};
 const visible=useMemo(()=>rows.filter(t=>{const hay=(t.title+" "+t.contact_name+" "+t.owner_name+" "+t.trip_name).toLowerCase();const q=hay.includes(query.toLowerCase());const f=filter==="all"||(filter==="open"&&t.status!=="done")||(filter==="today"&&isToday(t))||(filter==="overdue"&&isOverdue(t))||(filter==="done"&&t.status==="done");return q&&f}),[rows,query,filter]);
 function resetForm(){setEditing(null);setTitle("");setPriority("normal");setDueAt("");setContactId("");setOwnerId("");setTaskType("follow_up")}
 function openNew(){resetForm();setShowForm(true)}
 function openEdit(t:Task){setEditing(t);setTitle(t.title);setPriority(t.priority||"normal");setDueAt(t.due_at?new Date(t.due_at).toISOString().slice(0,16):"");setContactId(t.contact_id||"");setOwnerId(t.owner_id||"");setTaskType(t.task_type||"follow_up");setShowForm(true)}
 async function saveTask(){if(!title.trim()||saving)return;setSaving(true);const payload={title:title.trim(),priority,task_type:taskType,due_at:dueAt?new Date(dueAt).toISOString():null,contact_id:contactId||null,owner_id:ownerId||null,status:editing?.status||"open"};if(editing){const {error}=await supabase.from("tasks").update(payload).eq("id",editing.id);if(!error)setRows(v=>v.map(x=>x.id===editing.id?{...x,...payload,contact_name:contacts.find(c=>c.id===contactId)?.name||"Sin contacto",owner_name:owners.find(o=>o.id===ownerId)?.name||"Sin asignar"}:x))}else{const {data,error}=await supabase.from("tasks").insert(payload).select("id,title,due_at,priority,status,task_type,contact_id,owner_id,opportunity_id").single();if(!error&&data)setRows(v=>[{...data,contact_name:contacts.find(c=>c.id===contactId)?.name||"Sin contacto",owner_name:owners.find(o=>o.id===ownerId)?.name||"Sin asignar",trip_name:"—"},...v])}setSaving(false);setShowForm(false);resetForm()}
 async function setDone(t:Task,done:boolean){const patch={status:done?"done":"open",completed_at:done?new Date().toISOString():null};const {error}=await supabase.from("tasks").update(patch).eq("id",t.id);if(!error)setRows(v=>v.map(x=>x.id===t.id?{...x,status:patch.status}:x))}
 return <>
  <section className="opsMetricGrid"><article><div className="opsMetricIcon"><ListTodo size={19}/></div><div><span>Pendientes</span><strong>{stats.open}</strong><small>tareas abiertas</small></div></article><article><div className="opsMetricIcon good"><Clock3 size={19}/></div><div><span>Para hoy</span><strong>{stats.today}</strong><small>requieren atención hoy</small></div></article><article><div className="opsMetricIcon warn"><CircleAlert size={19}/></div><div><span>Vencidas</span><strong>{stats.overdue}</strong><small>seguimientos fuera de fecha</small></div></article><article><div className="opsMetricIcon good"><CheckCircle2 size={19}/></div><div><span>Completadas</span><strong>{stats.done}</strong><small>historial de resolución</small></div></article></section>
  <section className="opsCard" style={{overflow:"hidden"}}><div className="opsCardToolbar"><div className="opsInlineSearch"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar tarea, contacto, viaje o responsable..."/></div><div style={{display:"flex",gap:8,alignItems:"center",flexWrap:"wrap",justifyContent:"flex-end"}}><div className="opsFilterTabs">{[["open","Pendientes"],["today","Hoy"],["overdue","Vencidas"],["done","Completadas"],["all","Todas"]].map(([k,l])=><button key={k} className={filter===k?"active":""} onClick={()=>setFilter(k)}>{l}</button>)}</div><button className="opsPrimaryBtn" onClick={openNew}><Plus size={15}/> Nueva tarea</button></div></div>
  <div className="taskOpsHeader"><span>Tarea</span><span>Contacto</span><span>Viaje</span><span>Responsable</span><span>Vencimiento</span><span>Acciones</span></div>
  {visible.length?visible.map(t=><div key={t.id} className={"taskOpsRow "+(isOverdue(t)?"overdue":"")}><div className="taskOpsTitle"><i className={t.status==="done"?"done":t.priority==="high"?"high":t.priority==="low"?"low":"normal"}/><span><b>{t.title}</b><small>{t.task_type||"seguimiento"} · {t.priority||"normal"}</small></span></div><span>{t.contact_id?<Link href={"/crm/contacto/"+t.contact_id}><b>{t.contact_name}</b></Link>:<small>Sin contacto</small>}</span><span>{t.trip_name||"—"}</span><span>{t.owner_name||"Sin asignar"}</span><span><b className={isOverdue(t)?"taskDueOver":""}>{t.due_at?new Date(t.due_at).toLocaleDateString("es-AR"):"Sin fecha"}</b><small>{t.due_at?new Date(t.due_at).toLocaleTimeString("es-AR",{hour:"2-digit",minute:"2-digit"}):""}</small></span><span className="taskOpsActions">{t.status==="done"?<button className="opsSecondaryBtn" onClick={()=>setDone(t,false)} title="Reabrir"><RotateCcw size={14}/></button>:<button className="opsSecondaryBtn" onClick={()=>setDone(t,true)} title="Completar"><CheckCircle2 size={14}/></button>}<button className="opsSecondaryBtn" onClick={()=>openEdit(t)}>Editar</button></span></div>):<div className="taskOpsEmpty">No hay tareas para este filtro.</div>}</section>
  {showForm&&<div className="taskDrawerBackdrop" onClick={()=>setShowForm(false)}><aside className="taskDrawer" onClick={e=>e.stopPropagation()}><header><div><small>TAREA</small><h2>{editing?"Editar tarea":"Nueva tarea"}</h2></div><button className="opsIconBtn" onClick={()=>setShowForm(false)}><X size={17}/></button></header><div className="taskDrawerForm"><label>Título<input value={title} onChange={e=>setTitle(e.target.value)} style={fieldStyle}/></label><label>Tipo<select value={taskType} onChange={e=>setTaskType(e.target.value)} style={fieldStyle}><option value="follow_up">Seguimiento</option><option value="call">Llamada</option><option value="payment">Pago</option><option value="document">Documentación</option><option value="message">Mensaje</option></select></label><label>Prioridad<select value={priority} onChange={e=>setPriority(e.target.value)} style={fieldStyle}><option value="low">Baja</option><option value="normal">Normal</option><option value="high">Alta</option></select></label><label>Contacto<select value={contactId} onChange={e=>setContactId(e.target.value)} style={fieldStyle}><option value="">Sin contacto</option>{contacts.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Responsable<select value={ownerId} onChange={e=>setOwnerId(e.target.value)} style={fieldStyle}><option value="">Sin asignar</option>{owners.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label><label>Fecha y hora<input type="datetime-local" value={dueAt} onChange={e=>setDueAt(e.target.value)} style={fieldStyle}/></label><button className="opsPrimaryBtn" style={{justifyContent:"center",marginTop:8}} disabled={saving} onClick={saveTask}>{saving?"Guardando...":editing?"Guardar cambios":"Crear tarea"}</button></div></aside></div>}
 </>
}
